### ISSUE TITLE
Problem in using horizontal scaling feature

### ISSUE THREAD

**Issue by poorva29** [gilmour-libs/gilmour#5]
On Using - 
`listen_to 'my.message', true`
stack trace found is -

```
undefined local variable or method `excl' for #<Gilmour::RedisBackend:0x00000005671830>
/home/poorva/.rvm/gems/ruby-2.0.0-p353/bundler/gems/gilmour-1010c61d3d13/lib/gilmour/backends/redis.rb:93:in `add_listener'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:150:in `_add_listener'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:144:in `block (2 levels) in add_listeners'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:142:in `each'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:142:in `block in add_listeners'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:141:in `each'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:141:in `add_listeners'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:134:in `setup_geofence_listeners'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:100:in `update_config'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:47:in `block in setup_initial_geofence'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/dataset/actions.rb:143:in `block in each'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/adapters/oracle.rb:413:in `block in fetch_rows'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/adapters/oracle.rb:88:in `block in _execute'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/database/connecting.rb:229:in `block in synchronize'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/database/connecting.rb:229:in `synchronize'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/adapters/oracle.rb:75:in `_execute'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/adapters/oracle.rb:65:in `execute'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/dataset/actions.rb:795:in `execute'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/adapters/oracle.rb:404:in `fetch_rows'
/home/poorva/.rvm/gems/ruby-2.0.0-p353/gems/sequel-4.7.0/lib/sequel/dataset/actions.rb:143:in `each'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:46:in `setup_initial_geofence'
/home/poorva/tuts-rails/microservices/geofence/subscribers/geofence.rb:42:in `setup'
/home/poorva/tuts-rails/microservices/base_container.rb:22:in `block in initialize'
/home/poorva/tuts-rails/microservices/base_container.rb:19:in `each'
/home/poorva/tuts-rails/microservices/base_container.rb:19:in `initialize'
```

**Comment by poorva29** [comment]
This problem persists because gem version is not updated.
Please feel free to close this issue once the gem version is updated.

**Comment by adityagodbole** [comment]
Closing issue
